M48
; DRILL file {KiCad (5.99.0-12974-ge12f9a194d)} date 2021 November 21, Sunday 23:45:16
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-11-21T23:45:16-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-12974-ge12f9a194d)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X1.0476Y-2.2203
X1.2752Y-2.2203
T0
M30
